// This file is generated automatically by Next.js
// Do not edit this file manually
// This file validates that all pages and layouts export the correct types

import type { AppRoutes, LayoutRoutes, ParamMap } from "./routes.js"
import type { ResolvingMetadata, ResolvingViewport } from "next/types.js"

type AppPageConfig<Route extends AppRoutes = AppRoutes> = {
  default: React.ComponentType<{ params: Promise<ParamMap[Route]> } & any> | ((props: { params: Promise<ParamMap[Route]> } & any) => React.ReactNode | Promise<React.ReactNode> | never | void | Promise<void>)
  generateStaticParams?: (props: { params: ParamMap[Route] }) => Promise<any[]> | any[]
  generateMetadata?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingMetadata
  ) => Promise<any> | any
  generateViewport?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingViewport
  ) => Promise<any> | any
  metadata?: any
  viewport?: any
}

type LayoutConfig<Route extends LayoutRoutes = LayoutRoutes> = {
  default: React.ComponentType<LayoutProps<Route>> | ((props: LayoutProps<Route>) => React.ReactNode | Promise<React.ReactNode> | never | void | Promise<void>)
  generateStaticParams?: (props: { params: ParamMap[Route] }) => Promise<any[]> | any[]
  generateMetadata?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingMetadata
  ) => Promise<any> | any
  generateViewport?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingViewport
  ) => Promise<any> | any
  metadata?: any
  viewport?: any
}


// Validate ../../app/admin/auditoria/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/auditoria">> = Specific
  const handler = {} as typeof import("../../app/admin/auditoria/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/admin/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin">> = Specific
  const handler = {} as typeof import("../../app/admin/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/admin/usuarios/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/usuarios">> = Specific
  const handler = {} as typeof import("../../app/admin/usuarios/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/app/candidato/candidaturas/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/app/candidato/candidaturas">> = Specific
  const handler = {} as typeof import("../../app/app/candidato/candidaturas/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/app/candidato/denuncias/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/app/candidato/denuncias">> = Specific
  const handler = {} as typeof import("../../app/app/candidato/denuncias/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/app/candidato/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/app/candidato">> = Specific
  const handler = {} as typeof import("../../app/app/candidato/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/app/conta/privacidade/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/app/conta/privacidade">> = Specific
  const handler = {} as typeof import("../../app/app/conta/privacidade/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/app/contratante/denuncias/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/app/contratante/denuncias">> = Specific
  const handler = {} as typeof import("../../app/app/contratante/denuncias/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/app/contratante/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/app/contratante">> = Specific
  const handler = {} as typeof import("../../app/app/contratante/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/app/contratante/vagas/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/app/contratante/vagas">> = Specific
  const handler = {} as typeof import("../../app/app/contratante/vagas/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/app/equipe/denuncias/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/app/equipe/denuncias">> = Specific
  const handler = {} as typeof import("../../app/app/equipe/denuncias/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/app/equipe/moderacao/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/app/equipe/moderacao">> = Specific
  const handler = {} as typeof import("../../app/app/equipe/moderacao/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/app/equipe/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/app/equipe">> = Specific
  const handler = {} as typeof import("../../app/app/equipe/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/app/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/app">> = Specific
  const handler = {} as typeof import("../../app/app/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/conta-indisponivel/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/conta-indisponivel">> = Specific
  const handler = {} as typeof import("../../app/conta-indisponivel/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/laboratorio-ui/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/laboratorio-ui">> = Specific
  const handler = {} as typeof import("../../app/laboratorio-ui/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/onboarding/candidato/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/onboarding/candidato">> = Specific
  const handler = {} as typeof import("../../app/onboarding/candidato/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/onboarding/contratante/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/onboarding/contratante">> = Specific
  const handler = {} as typeof import("../../app/onboarding/contratante/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/">> = Specific
  const handler = {} as typeof import("../../app/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/recuperar-senha/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/recuperar-senha">> = Specific
  const handler = {} as typeof import("../../app/recuperar-senha/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/vagas/[id]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/vagas/[id]">> = Specific
  const handler = {} as typeof import("../../app/vagas/[id]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/vagas/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/vagas">> = Specific
  const handler = {} as typeof import("../../app/vagas/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}







// Validate ../../app/admin/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/admin">> = Specific
  const handler = {} as typeof import("../../app/admin/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/app/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/app">> = Specific
  const handler = {} as typeof import("../../app/app/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/">> = Specific
  const handler = {} as typeof import("../../app/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}
